src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]

    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profile_picture = null;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'seller', orphanRemoval: true)]
    private Collection $articles;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'sender')]
    private Collection $messages;

    /**
     * @var Collection<int, Favorite>
     */
    #[ORM\OneToMany(targetEntity: Favorite::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $favorites;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->buyed_articles = new ArrayCollection();
    }

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private bool $isVerified = false;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'buyer')]
    private Collection $buyed_articles;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */

    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(?string $profile_picture): static
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setSeller($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getSeller() === $this) {
                $article->setSeller(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setSender($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getSender() === $this) {
                $message->setSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Favorite>
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): static
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites->add($favorite);
            $favorite->setUser($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): static
    {
        if ($this->favorites->removeElement($favorite)) {
            // set the owning side to null (unless already changed)
            if ($favorite->getUser() === $this) {
                $favorite->setUser(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getBuyedArticles(): Collection
    {
        return $this->buyed_articles;
    }

    public function addBuyedArticle(Article $buyedArticle): static
    {
        if (!$this->buyed_articles->contains($buyedArticle)) {
            $this->buyed_articles->add($buyedArticle);
            $buyedArticle->setBuyer($this);
        }

        return $this;
    }

    public function removeBuyedArticle(Article $buyedArticle): static
    {
        if ($this->buyed_articles->removeElement($buyedArticle)) {
            // set the owning side to null (unless already changed)
            if ($buyedArticle->getBuyer() === $this) {
                $buyedArticle->setBuyer(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Message;
use App\Form\SendMessageType;
use App\Form\BuyFormType;
use App\Form\FormSellType;
use App\Service\CallRequest;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Twig\Environment;

#[IsGranted('IS_AUTHENTICATED_FULLY')]
class MainController extends AbstractController
{
    private $notificationCount;

    public function __construct(
        private CallRequest $callRequest,
        private EntityManagerInterface $entityManager,
        private Environment $twig,
    ) {
        $this->notificationCount = $this->callRequest->GetNotificationCount();

        $this->twig->addGlobal('notification_count', $this->notificationCount);
    }

    #[Route('/category/{category}', name: 'category')]
    public function category(string $category): Response
    {
        $allArticle = $this->callRequest->GetAllArticleByCategory($category);

        return $this->render('main/home.html.twig', [
            'all_article' => $allArticle
        ]);
    }

    #[Route('/article/{id}', name: 'article')]
    public function article(int $id): Response
    {
        $article = $this->entityManager->getRepository(Article::class)->find($id);

        $callRequest = $this->callRequest;

        $user = $this->getUser();

        return $this->render('main/article.html.twig', [
            'article' => $article,
            'call_request' => $callRequest,
            'user' => $user
        ]);
    }

    #[Route('/profile', name: 'profile')]
    public function profile(): Response
    {
        $user = $this->getUser();

        return $this->render('main/profile.html.twig', [
            'user' => $user
        ]);
    }

    #[Route('/receipts', name: 'receipts')]
    public function receipts(): Response
    {
        $user = $this->getUser();
        $soldArticle = $this->callRequest->GetSoldArticle();
        $receipts = $this->callRequest->GetReceipts($soldArticle);

        return $this->render('main/receipts.html.twig', [
            'user' => $user,
            'sold_article' => $soldArticle,
            'receipts' => $receipts
        ]);
    }


    #[Route('/sell', name: 'sell')]
    public function sell(
        Request $request,
        EntityManagerInterface $entityManager,
    ) {
        $sellArticle = new Article();
        $form = $this->createForm(FormSellType::class, $sellArticle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sellArticle->setSeller($this->getUser());

            $imageFile = $form->get('picture')->getData();
            $fileName = $sellArticle->getId() . '.jpg';

            // Move the file to the directory where images are stored
            $imageFile->move(
                $this->getParameter('images_directory'), // Defined in your config/services.yaml
                $fileName
            );

            $sellArticle->setPicture("img/" . $fileName);

            $entityManager->persist($sellArticle);
            $entityManager->flush();

            return $this->redirectToRoute('article', [
                'id' => $sellArticle->getId()
            ]);
        }

        return $this->render('main/sell.html.twig', [
            'form_sell' => $form,
        ]);
    }

    #[Route('/edit-article/{id}', name: 'edit_article')]
    public function editArticle(
        Request $request,
        EntityManagerInterface $entityManager,
        int $id
    ) {
        $editArticle = $this->callRequest->GetArticle($id);
        $form = $this->createForm(FormSellType::class, $editArticle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $imageFile = $form->get('picture')->getData();
            $fileName = $editArticle->getId() . '.jpg';

            // Move the file to the directory where images are stored
            $imageFile->move(
                $this->getParameter('images_directory'), // Defined in your config/services.yaml
                $fileName
            );

            $editArticle->setPicture("img/" . $fileName);

            $entityManager->persist($editArticle);
            $entityManager->flush();

            return $this->redirectToRoute('article', [
                'id' => $editArticle->getId()
            ]);
        }

        return $this->render('main/edit.html.twig', [
            'form_edit' => $form,
        ]);
    }

    #[Route('/message', name: 'message')]
    public function message(): Response
    {
        $messagedUser = $this->callRequest->GetAllMessagedUser();

        return $this->render('main/message_list.html.twig', [
            "messaged_user" => $messagedUser
        ]);
    }

    #[Route('/message/{receiverId}', name: 'messageCategory')]
    public function messageCategory(
        int $receiverId,
        Request $request,
        EntityManagerInterface $entityManager
    ): Response {
        if ($this->getUser()->getId() == $receiverId) { // don't care this fucking error
            return $this->redirectToRoute('message');
        }

        $receiver = $this->callRequest->GetUser($receiverId);
        $messageAllList = $this->callRequest->GetMessage($receiver);
        $seenAdded = $this->callRequest->setMessageSeen($messageAllList);

        $this->twig->addGlobal('notification_count', $this->notificationCount - $seenAdded);

        $message = new Message();
        $form = $this->createForm(SendMessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message->setSender($this->getUser());
            $message->setReceiver($receiver);

            $entityManager->persist($message);
            $entityManager->flush();

            return $this->redirectToRoute('messageCategory', [
                'receiverId' => $receiverId,
            ]);
        }

        return $this->render('main/message.html.twig', [
            'all_message' => $messageAllList,
            'send_message' => $form,
        ]);
    }

    #[Route('/buy/{id}', name: 'buy')]
    public function buy(
        int $id,
        Request $request,
        EntityManagerInterface $entityManager
    ): Response {
        $user = $this->getUser();
        $article = $this->callRequest->GetArticle($id);

        if ($article->getSeller() == $user) {
            return $this->redirectToRoute('home');
        }

        $form = $this->createForm(BuyFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article
                ->setStatus(true)
                ->setBuyer($user);

            $message = new Message();
            $message
                ->setSender($user)
                ->setReceiver($article->getSeller())
                ->setContent(
                    "User " .
                        $user->getName() .
                        " has bought your product " .
                        $article->getTitle() .
                        "."
                );

            $entityManager->persist($user);
            $entityManager->persist($article);
            $entityManager->persist($message);

            $entityManager->flush();

            return $this->redirectToRoute('buy_sucess');
        }
        return $this->render('main/buy.html.twig', [
            'buy_user' => $form,

        ]);
    }
    #[Route('/buysucess', name: 'buy_sucess')]
    public function buysucess(): Response
    {
        return $this->render('main/buysucess.html.twig');
    }

    #[Route(path: '/favorite', name: 'favorite')]
    public function favorite(): Response
    {
        $allFavorite = $this->callRequest->GetAllFavoris();

        return $this->render('main/favorite.html.twig', [
            'favorites' => $allFavorite
        ]);
    }

    #[Route(path: '/buyed', name: 'buyed')]
    public function buyed(): Response
    {
        $buyedArticle = $this->callRequest->GetBuyedArticleFromUser();

        return $this->render('main/buyed.html.twig', [
            'selledArticle' => $buyedArticle
        ]);
    }

    #[Route(path: '/my-product', name: 'my_product')]
    public function selled(): Response
    {
        $selledArticle = $this->callRequest->GetSelledArticleFromUser();

        return $this->render('main/myproduct.html.twig', [
            'selledArticle' => $selledArticle
        ]);
    }
}

templates/main/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1.5em auto;
			max-width: 800px;
			width: 90%;
			font-family: 'Arial', sans-serif;
			color: #333;
			background: #f8f9fa;
			padding: 15px;
			border-radius: 6px;
			box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
		}

		.example-wrapper h1 {
			font-size: 24px; /* Titre plus petit */
			margin-bottom: 15px;
			color: #007bff;
			text-align: center;
		}

		.example-wrapper img {
			display: block;
			width: 100%;
			height: auto;
			max-height: 300px; /* Taille de l'image réduite */
			margin: 0 auto 15px;
			object-fit: cover;
			border-radius: 6px;
			box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
		}

		.example-wrapper p {
			font-size: 16px; /* Taille de police plus petite */
			line-height: 1.4;
			margin-bottom: 8px;
		}

		.category, .price {
			text-align: center;
			font-size: 18px;
		}

		/* Réduction de l'espacement autour du prix */
		.price {
			color: #28a745;
			font-weight: bold;
			margin: 15px 0;
		}

		/* Boutons */
		.buttons {
			display: flex;
			justify-content: center;
			margin-top: 20px;
			gap: 10px; /* Espacement réduit entre les boutons */
		}

		.buttons a {
			padding: 8px 12px; /* Boutons plus compacts */
			font-size: 14px; /* Taille de texte réduite */
			color: white;
			border-radius: 6px;
			text-decoration: none;
			transition: background-color 0.3s ease-in-out;
		}

		/* Couleurs des boutons */
		.buttons a {
			background-color: #007bff;
		}

		.buttons a:nth-child(2) {
			background-color: #17a2b8; /* Contact */
		}

		.buttons a:nth-child(3) {
			background-color: #e83e8c; /* Ajouter aux favoris */
		}

		.buttons a:nth-child(4) {
			background-color: #ffc107; /* Modifier */
		}

		.buttons a:nth-child(5) {
			background-color: #dc3545; /* Supprimer */
		}

		/* Effet au survol */
		.buttons a:hover {
			opacity: 0.9;
			transform: translateY(-1px); /* Effet plus subtil */
		}

		/* Ajustements de transition */
		.example-wrapper img,
		.buttons a {
			transition: all 0.3s ease;
		}
	</style>

	<div class="example-wrapper">
		<h1>{{ article.title }}</h1>

		<img src="{{ asset(article.picture) }}" onerror="this.onerror=null;this.src='{{ article.picture }}';" alt="{{ article.title }}">

		<p>{{ article.description }}</p>
		<p class="category">{{ article.category }}</p>
		<p class="price">{{ article.price }}€</p>

		<div class="buttons">
			{% if app.user != article.seller %}
				<a href="{{ path('buy', {'id': article.id} ) }}">Buy</a>
				<a href="{{ path('messageCategory', {'receiverId': article.seller.id} ) }}">Contact seller</a>
				<a href="{{ path('add_favorite', {'article_id': article.id} ) }}">💜 Add to Favorites</a>
			{% else %}
				<a href="{{ path('edit_article', {'id': article.id} ) }}">Edit</a>
				<a href="{{ path('delete_article', {'article': article.id} ) }}">Delete</a>
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/main/buy.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font-size: 18px;
			line-height: 1.5;
			padding: 20px;
			background: white;
			border-radius: 8px;
			box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
		}

		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
			border-radius: 4px;
		}

		h1 {
			color: purple;
			text-align: center;
			margin-bottom: 1em;
		}

		button {
			background-color: purple;
			color: white;
			border: none;
			border-radius: 4px;
			padding: 10px 15px;
			cursor: pointer;
			transition: background-color 0.3s;
		}

		button:hover {
			background-color: darkviolet;
		}

		.form-group {
			margin-bottom: 1.5em;
		}

		label {
			display: block;
			margin-bottom: 0.5em;
			font-weight: bold;
		}

		input,
		select,
		textarea {
			width: 100%;
			padding: 10px;
			border: 1px solid #ccc;
			border-radius: 4px;
			box-sizing: border-box;
		}

		input:focus,
		select:focus,
		textarea:focus {
			border-color: purple;
			outline: none;
		}
	</style>

	<div class="example-wrapper">
		<h1>Delivery information</h1>
		{{form(buy_user)}}


		</div>
	{% endblock %}

templates/main/buyed.html.twig
{% extends 'base.html.twig' %}

{% block title %}Buyed{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1.5em auto;
			max-width: 900px;
			width: 95%;
			font-family: 'Arial', sans-serif;
			color: #333;
		}

		/* Container pour chaque carte */
		.card {
			display: flex;
			align-items: center;
			background: #f8f9fa;
			margin-bottom: 15px;
			padding: 15px;
			border-radius: 8px;
			box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
			transition: box-shadow 0.3s ease-in-out;
		}

		.card:hover {
			box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
		}

		/* Image dans la carte */
		.card img {
			width: 150px;
			height: 100px;
			border-radius: 6px;
			object-fit: cover;
			margin-right: 20px;
		}

		/* Informations de l'article */
		.card-info {
			flex: 1;
		}

		.card-info h1 {
			font-size: 20px;
			color: #007bff;
			margin: 0 0 10px;
		}

		.card-info p {
			font-size: 16px;
			color: #6c757d;
			margin: 0 0 10px;
		}

		.card-info .price {
			font-size: 18px;
			color: #28a745;
			font-weight: bold;
		}

		/* Liens des articles */
		.card a {
			text-decoration: none;
			color: inherit;
		}

		.card a:hover h1 {
			color: #0056b3;
		}

	</style>

	<div class="example-wrapper">
		<h1>Your Purchased Articles</h1>
		{% if selledArticle|length > 0 %}
			{% for article in selledArticle %}
				<a href="{{ path('article', {'id': article.id}) }}" class="card">
					<img src="{{ article.picture }}" alt="{{ article.title }}">
					<div class="card-info">
						<h1>{{ article.title }}</h1>
						<p>{{ article.description }}</p>
						<p class="price">{{ article.price }}€</p>
					</div>
				</a>
			{% endfor %}
		{% else %}
			<p>You haven't bought any articles yet.</p>
		{% endif %}
	</div>
{% endblock %}

templates/main/buysucess.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
		p {
			color: purple;
			text-align: center;
			font-size: 20px;

		}
		.flex {
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%, -50%);
			text-align: center;
		}
	</style>

	<div class="example-wrapper">
		<div class="flex">
			<p>Thank you for your purchase. A message has been sent to the seller, you can contact them for more information.</p>
		</div>

	</div>
{% endblock %}

templates/main/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit
{% endblock %}

{% block body %}

	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}

		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font-size: 18px;
			line-height: 1.5;
			padding: 20px;
			background: white;
			border-radius: 8px;
			box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
		}

		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
			border-radius: 4px;
		}

		h1 {
			color: purple;
			text-align: center;
			margin-bottom: 1em;
		}

		button {
			background-color: purple;
			color: white;
			border: none;
			border-radius: 4px;
			padding: 10px 15px;
			cursor: pointer;
			transition: background-color 0.3s;
		}

		button:hover {
			background-color: darkviolet;
		}

		.form-group {
			margin-bottom: 1.5em;
		}

		label {
			display: block;
			margin-bottom: 0.5em;
			font-weight: bold;
		}

		input,
		select,
		textarea {
			width: 100%;
			padding: 10px;
			border: 1px solid #ccc;
			border-radius: 4px;
			box-sizing: border-box;
		}

		input:focus,
		select:focus,
		textarea:focus {
			border-color: purple;
			outline: none;
		}
	</style>

	<div>
		<h1>Edit your article!</h1>
		{{form(form_edit)}}
	</div>
	{% endblock %}

templates/main/message.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font-family: 'Arial', sans-serif;
		}
		.container {
			margin: 1em 0;
			padding: 1em;
			border-radius: 10px;
			background-color: #f9f9f9;
			box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
			position: relative;
		}
		.sender,
		.receiver {
			font-weight: bold;
			font-size: 1.1em;
			margin-bottom: 0.5em;
		}
		.sender {
			color: #34495e;
		}
		.receiver {
			text-align: right;
			color: #2980b9;
		}
		.content {
			padding: 0.5em;
			background-color: #e7f3fe;
			border-left: 5px solid #2980b9;
		}
		.timestamp {
			font-size: 0.85em;
			color: #7f8c8d;
			margin-top: 0.5em;
			text-align: left;
		}
	</style>

	<div class="example-wrapper">

		{% for message in all_message %}

			<div class="container">
				<div class="sender">{{message.sender.name}}</div>
				<div class="container-2">
					<div class="content">{{message.content}}</div>
				</div>
				<div>{{message.date|date("d-m-Y H:i")}}</div>
				<div class="receiver">{{message.receiver.name}}</div>
			</div>

		{% endfor %}

		{{form_start(send_message)}}
		{{form_widget(send_message.content, { 'attr': {'placeholder': 'message...', 'rows': 3} })}}
		{{form_widget(send_message.Send)}}
		{{form_end(send_message)}}

	</div>
{% endblock %}

templates/main/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1.5em auto;
			max-width: 700px;
			width: 90%;
			font-family: 'Arial', sans-serif;
			color: #333;
			background: #f8f9fa;
			padding: 20px;
			border-radius: 8px;
			box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
			text-align: center; /* Centrage du contenu */
		}

		.example-wrapper h1 {
			font-size: 28px;
			margin-bottom: 10px;
			color: #007bff;
		}

		.example-wrapper h6 {
			font-size: 16px;
			margin-bottom: 20px;
			color: #6c757d;
		}

		.example-wrapper img {
			width: 150px;
			height: 150px;
			border-radius: 50%; /* Cercle pour l'image de profil */
			object-fit: cover;
			margin-bottom: 20px;
			box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
		}

		/* Style des boutons */
		.example-wrapper li {
			list-style: none; /* Suppression des puces */
			margin-bottom: 10px;
		}

		.example-wrapper li a {
			display: inline-block;
			padding: 10px 20px;
			font-size: 16px;
			color: white;
			background-color: #007bff;
			border-radius: 6px;
			text-decoration: none;
			transition: background-color 0.3s ease-in-out;
		}

		/* Effet au survol */
		.example-wrapper li a:hover {
			background-color: #0056b3; /* Changement de couleur au survol */
		}

		/* Espacement entre les boutons */
		.buttons {
			display: flex;
			flex-direction: column;
			align-items: center;
			gap: 10px;
		}

	</style>

	<div class="example-wrapper">
		<h1>Profile of {{ user.name }}</h1>
		<h6>{{ user.email }}</h6>

		<img src="{{ user.profilePicture }}" alt="{{ user.name }}'s profile picture">

		<div class="buttons">
			<li>
				<a href="{{ path('favorite') }}">Favorite</a>
			</li>
			<li>
				<a href="{{ path('buyed') }}">Buyed</a>
			</li>
			<li>
				<a href="{{ path('my_product') }}">My Product</a>
			</li>
			<li>
				<a href="{{ path('receipts') }}">Receipts</a>
			</li>
		</div>
	</div>
{% endblock %}